#!/bin/sh

. ./functions.sh
check_and_source_constants

# Experience has shown that using a file system in RAM speeds up the build
# process between 5 to 10 times in comparison to using a file system on SSDs or
# classical hard drives with spinning rust.
# Unfortunately, tmpfs doesn't support extended attributes but they are needed
# by some tools during installation, e.g. flatpak. Therefore we can't use
# tmpfs mounts directly but must create an additional image inside the tmpfs
# that must be formatted with another file system that supports extended
# attributes (e.g. ext4).

if findmnt "${TMPFS}" > /dev/null
then
	echo "[INFO] : found tmpfs mounted on \"${TMPFS}\""
	if findmnt "${TMPFS_IMAGE_MOUNT}" > /dev/null
	then
		echo "[INFO] : found tmpfs image mounted on \"${TMPFS_IMAGE_MOUNT}\""
	else
		echo "[WARNING] : no tmpfs image mounted on \"${TMPFS_IMAGE_MOUNT}\" found"
		echo "[INFO] : execute 'build_tmpfs.sh'"
		exit 1
	fi
else
	echo "[WARNING] : There is no mounted filesystem in \"${TMPFS}\"."
	echo "[INFO] : execute 'build_tmpfs.sh'"
	exit 1
fi

PWD="$(pwd)"

lb clean --all

## Copy configurations from template to chroot env.
if [ -d "${TMPFS_IMAGE_MOUNT}/config" ]; then rm -rf "${TMPFS_IMAGE_MOUNT}/config"; fi

cp -a "${PWD}/config" "${TMPFS_IMAGE_MOUNT}"

## Check link to cache directory.
if [ -L "${TMPFS_IMAGE_MOUNT}/cache" ] ; then
   if [ -e "${TMPFS_IMAGE_MOUNT}/cache" ] ; then
      echo "[INFO] : The link to '${TMPFS_IMAGE_MOUNT}/cache' -> '${PWD}/cache' already exists."
   else
      echo "[ERROR] : The link to '${TMPFS_IMAGE_MOUNT}/cache' is a broken link."
      exit 1
   fi
elif [ -e "${TMPFS_IMAGE_MOUNT}/cache" ] ; then
   echo "[WARNING] : The link to '${TMPFS_IMAGE_MOUNT}/cache' is not a link."
else
   echo "[INFO] : Creating proper '${TMPFS_IMAGE_MOUNT}/cache' -> '${PWD}/cache' link."
   ln -s "${PWD}/cache" "${TMPFS_IMAGE_MOUNT}"
fi

## Check link to templates directory.
if [ -L "${TMPFS_IMAGE_MOUNT}/themes" ] ; then
   if [ -e "${TMPFS_IMAGE_MOUNT}/themes" ] ; then
      echo "[INFO] : The link to '${TMPFS_IMAGE_MOUNT}/themes' -> '${PWD}/themes' already exists."
   else
      echo "[ERROR] : The link to '${TMPFS_IMAGE_MOUNT}/themes' is a broken link."
      exit 1
   fi
elif [ -e "${TMPFS_IMAGE_MOUNT}/themes" ] ; then
   echo "[WARNING] : The link to '${TMPFS_IMAGE_MOUNT}/themes' is not a link."
else
   echo "[INFO] : Creating proper '${TMPFS_IMAGE_MOUNT}/themes' -> '${PWD}/themes' link."
   ln -s "${PWD}/themes" "${TMPFS_IMAGE_MOUNT}"
fi


