^(http|https)://moodle\.msengineering\.ch
^https://[a-zA-Z]+\.switch\.ch
^https://wayf\.switch\.ch/SWITCHaai
^https://[a-zA-Z]+\.login\.eduid\.ch/favicon\.ico$
^https://[a-zA-Z]+.login.eduid.ch
^https://login\.eduid.\ch
^https://static\.eduid\.ch
^https://drive\.switch\.ch/index\.php/s/NnNaOgN4lHaqe2M
^https://drive\.switch\.ch/index\.php/s/tQLKBilUJ7l8DLj
