[keyfile]
# ac:de:48:00:11:22 is the QEMU/KVM virtual NIC vendor MAC prefix.
# Unmanaging this prevents NetworkManager from managing virtual bridge
# interfaces on exam machines running as QEMU/KVM guests.
unmanaged-devices=mac:ac:de:48:00:11:22